package bStat.ims.com.common.exceptions;

/**
 * Created by prashant170392 on 01/05/2017
 */
public enum ResponseErrorMsg {
    VALIDATION_ERROR,
    INVALID_CLIENT_ID,
    DUPLICATE_REQUEST,
    INVALID_TEMPLATE,
    RUNTIME_ERROR,
    NOT_CANCELABLE,
    ALREADY_CANCELED,
    NOT_AVAILABLE,
    ALREADY_CONCLUDED,
    NO_MORE_CODES_AVAILABLE,
    CAN_NOT_POPULATE_VARIABLES,
    DOWNSTREAM_ERROR
}
