server:
  #adminMinThreads: 1
  #adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: ALL
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{0} [%X{id}] %msg%n"
      currentLogFilename: /var/log/bStat/IMS/ims.log
      archive: true
      archivedLogFilenamePattern: /var/log/bStat/IMS/ims-%d{yyyy-MM-dd}.log
      archivedFileCount: 20

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: GAneshjI
  # the JDBC URL
  url: jdbc:mysql://localhost:3306/bstat-ims-db
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: create
    hibernate.generate_statistics : false

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  maxConnectionAge : 10s

configParams:
  protocol: http
  server: localhost
  port: 80
  timeOut: 5000
  apiVersion: 1
  bucket: bstat-IMS